CREATE DATABASE `checkprinting` /*!40100 DEFAULT CHARACTER SET latin1 */;

DROP TABLE IF EXISTS `checkprinting`.`checkprinting`;
CREATE TABLE  `checkprinting`.`checkprinting` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `WorkCompleteFlag` int(10) unsigned DEFAULT NULL,
  `PDF_Form` longblob,
  `Error` text,
  `check_no` varchar(45) DEFAULT NULL,
  `client_id` varchar(45) DEFAULT NULL,
  `receiver_name` varchar(255) DEFAULT NULL,
  `payment_received` varchar(45) DEFAULT NULL,
  `originator_code` varchar(80) DEFAULT NULL,
  `pay_to_order_of` varchar(255) DEFAULT NULL,
  `amount` varchar(45) DEFAULT NULL,
  `for_field` varchar(255) DEFAULT NULL,
  `signature` varchar(45) DEFAULT NULL,
  `balance_check_amount` varchar(45) DEFAULT NULL,
  `routing_number` varchar(45) DEFAULT NULL,
  `account_number` varchar(45) DEFAULT NULL,
  `cusid` int(10) unsigned DEFAULT NULL,
  `ssn_husband` varchar(9) DEFAULT NULL,
  `account_alias` varchar(45) DEFAULT NULL,
  `posting_date` varchar(45) DEFAULT NULL,
  `effec_entry_date` varchar(45) DEFAULT NULL,
  `originator_name` varchar(45) DEFAULT NULL,
  `iden_no` varchar(45) DEFAULT NULL,
  `debit` varchar(45) DEFAULT NULL,
  `trans_type` varchar(45) DEFAULT NULL,
  `standard_ent_class_code` varchar(45) DEFAULT NULL,
  `id_no` varchar(45) DEFAULT NULL,
  `trace_no` varchar(45) DEFAULT NULL,
  `undefined` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3023 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `checkprinting`.`csv_datasource`;
CREATE TABLE  `checkprinting`.`csv_datasource` (
  `trace_no` varchar(255) NOT NULL,
  `account_number` varchar(45) DEFAULT NULL,
  `account_alias` varchar(45) DEFAULT NULL,
  `posting_date` varchar(45) DEFAULT NULL,
  `effec_entry_date` varchar(45) DEFAULT NULL,
  `receiver_name` varchar(45) DEFAULT NULL,
  `originator_name` varchar(45) DEFAULT NULL,
  `id_no` varchar(45) DEFAULT NULL,
  `debit` varchar(45) DEFAULT NULL,
  `amount` varchar(45) DEFAULT NULL,
  `trans_type` varchar(45) DEFAULT NULL,
  `standard_ent_class_code` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`trace_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `checkprinting`.`customer`;
CREATE TABLE  `checkprinting`.`customer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ssn` varchar(45) DEFAULT NULL,
  `PDF_Form` longblob,
  `WorkCompleteFlag` int(10) unsigned DEFAULT NULL,
  `Error` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `checkprinting`.`taxrefund`;
CREATE TABLE  `checkprinting`.`taxrefund` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `WorkCompleteFlag` int(10) unsigned DEFAULT NULL,
  `Error` text,
  `PDF_Form` longblob,
  `check_no` varchar(45) DEFAULT NULL,
  `order_transaction_id` varchar(45) DEFAULT NULL,
  `client_id` varchar(45) DEFAULT NULL,
  `receiver_name` varchar(255) DEFAULT NULL,
  `ssn_wife` varchar(9) DEFAULT NULL,
  `payment_received` varchar(45) DEFAULT NULL,
  `originator_code` varchar(80) DEFAULT NULL,
  `fee_title1` varchar(45) DEFAULT NULL,
  `fee_title2` varchar(45) DEFAULT NULL,
  `fee_title3` varchar(45) DEFAULT NULL,
  `fee_title4` varchar(45) DEFAULT NULL,
  `fee_title5` varchar(45) DEFAULT NULL,
  `fee_title6` varchar(45) DEFAULT NULL,
  `fee_title7` varchar(45) DEFAULT NULL,
  `fee_title8` varchar(45) DEFAULT NULL,
  `fee_amount1` varchar(45) DEFAULT NULL,
  `fee_amount2` varchar(45) DEFAULT NULL,
  `fee_amount3` varchar(45) DEFAULT NULL,
  `fee_amount4` varchar(45) DEFAULT NULL,
  `fee_amount5` varchar(45) DEFAULT NULL,
  `fee_amount6` varchar(45) DEFAULT NULL,
  `fee_amount7` varchar(45) DEFAULT NULL,
  `fee_amount8` varchar(45) DEFAULT NULL,
  `husband_signature` varchar(45) DEFAULT NULL,
  `husband_date` varchar(45) DEFAULT NULL,
  `wife_signature` varchar(45) DEFAULT NULL,
  `wife_date` varchar(45) DEFAULT NULL,
  `pay_to_order_of` varchar(255) DEFAULT NULL,
  `amount` varchar(45) DEFAULT NULL,
  `for_field` varchar(255) DEFAULT NULL,
  `signature` varchar(45) DEFAULT NULL,
  `balance_check_amount` varchar(45) DEFAULT NULL,
  `routing_number` varchar(45) DEFAULT NULL,
  `account_number` varchar(45) DEFAULT NULL,
  `cusid` int(10) unsigned DEFAULT NULL,
  `ssn_husband` varchar(9) DEFAULT NULL,
  `account_alias` varchar(45) DEFAULT NULL,
  `posting_date` varchar(45) DEFAULT NULL,
  `effec_entry_date` varchar(45) DEFAULT NULL,
  `originator_name` varchar(45) DEFAULT NULL,
  `iden_no` varchar(45) DEFAULT NULL,
  `debit` varchar(45) DEFAULT NULL,
  `trans_type` varchar(45) DEFAULT NULL,
  `standard_ent_class_code` varchar(45) DEFAULT NULL,
  `id_no` varchar(45) DEFAULT NULL,
  `trace_no` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1622 DEFAULT CHARSET=latin1;